### ISSUE TITLE
How to modify an Openstack port's allowed_address_pairs?

### ISSUE THREAD

**Issue by n-pochet** [inmanta/openstack#12]
I looked in the documentation, in the module's model and in the source code of the module but I never found a way to modify the parameter `allowed_address_pairs` for a specific port. Is it possible?
Thanks!

**Comment by bartv** [comment]
No. But we can add it. For router functions we normally disable port security.

**Comment by bartv** [comment]
@n-pochet Can you try the changes in pull request #15

**Comment by n-pochet** [comment]
When I try my model, I got an error:
```
Traceback (most recent call last):
  File "/usr/bin/inmanta", line 11, in <module>
    sys.exit(app())
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/app.py", line 382, in app
    options.func(options)
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/app.py", line 247, in export
    version, _ = export.run(types, scopes, metadata=metadata)
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/export.py", line 236, in run
    self._load_resources(types)
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/export.py", line 133, in _load_resources
    res = Resource.create_from_model(self, entity, DynamicProxy.return_value(instance))
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/resources.py", line 301, in create_from_model
    value = cls.map_field(exporter, entity_name, field, model_object)
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/resources.py", line 268, in map_field
    value = mthd(exporter, DynamicProxy.return_value(model_object))
  File "/root/ngfw-model/libs/openstack/plugins/__init__.py", line 242, in get_routes
    routes = {route.destination: route.nexthop for route in router.routes}
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/execute/proxy.py", line 106, in __getattr__
    value = instance.get_attribute(attribute).get_value()
  File "/opt/inmanta/lib64/python3.5/site-packages/inmanta/execute/runtime.py", line 325, in get_value
    raise OptionalValueException(self.myself, self.attribute)
inmanta.ast.OptionalValueException: Optional variable accessed that has no value (openstack::Router (instantiated at /root/ngfw-model/libs/openstack-instance/model/_init.cf:55).[0:1] routes)
```
Line 55 being:
```
router = openstack::Router(provider=provider, project=project, name="to_ext_router2", admin_state="up", ext_gateway=external_net)
```

**Comment by bartv** [comment]
Damn, stupid rewrite error. Whenever I'm waiting for unit tests to finish on the openstack module I rewrite old relation syntax :)

**Comment by n-pochet** [comment]
The first time that it creates it, there's no problem.
When it checks again for the deployment, it raises an error:
```
An error occurred during deployment of openstack::HostPort[iaas_openstack,name=source_port],v=1516957916 (exception: TypeError('list indices must be integers or slices, not str',))
```

**Comment by bartv** [comment]
Ok. Thx. Lets improve the testcase first then.

**Comment by bartv** [comment]
Really stupid mistake. Can you try again?

**Comment by n-pochet** [comment]
I don't see anymore errors for the moment.
